### PR TITLE
Use Min Periods in MTP ST

### PR DESCRIPTION
**Pull request by JeremyRubin**
Hey AJ,

just food for thought.

dual benefit of known start time, expected stop time, automatic extension of signaling periods in light of a hashrate decrease.

Perhaps not worth added complexity.

### CODE REVIEW

**Comment by ajtowns** [comment]
That would require tracking `min_stop_height` (or just the `StateSince` value) as part of the versionbits cache as well.

**Comment by JeremyRubin** [comment]
Ah, you're right. We only re-traverse if it's not in the cache. Let me patch...

**Comment by JeremyRubin** [comment]
I think that fixes the caching?

**Comment by ajtowns** [comment]
No? The stop height could change in a reorg, so has to be indexed on the block. Capturing the "since" height is pretty easy, and lets you avoid a second query in GetStateSinceHeight -- that's what I did in the trial implementation of [modern soft fork activation](https://github.com/ajtowns/bitcoin/commit/b00120a2ef0de89556c05879048ef58e4d652d24#diff-73b381667b1bb315180fc7e7a66992e79ad742972de5d0d2c1b8404d3d67e1b0R86)

**Comment by JeremyRubin** [comment]
the stop height gets reset any time the state machine transitions back into DEFINED though, right?

**Pull request closed without merging**
